FROM registry.access.redhat.com/ubi8/openjdk-17:1.19

COPY target/quakcus-app/lib/ /deployments/lib/
COPY target/quakcus-app/quarkus-run.jar /deployments/quarkus-run.jar

EXPOSE 8080
USER 185

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]