####
# Dockerfile for running the Quarkus application in JVM mode
#
# Build the application first:
#   ./mvnw clean package
#
# Then build the image:
#   docker build -f src/main/docker/Dockerfile.jvm -t myorg/warehouse-api .
#
# Run the container:
#   docker run -i --rm -p 8080:8080 myorg/warehouse-api
####

FROM registry.access.redhat.com/ubi8/openjdk-17:1.19

ENV LANGUAGE='en_US:en'

# Copy Quarkus fast-jar layout
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/

EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]